server:
  port: 8080
spring:
  application:
    name: eureka-client2
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
   
