server:
  port: 8085

spring:
  application:
    name: eureka-sleuth
  cloud:
    config:
      uri: http://localhost:9999 # 配置服务的地址
      name: eureka-sleuth  # 指的是读取文件类型为application类型的配置文件
      profile: dev # 指的是读取eureka-serverh和test的application配置文件，即读取配置文件服务器的eureka-server-application.yml和application-test.yml配置文件
