server:
  port: 8090
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      default-filters:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称j进行路由
      routes:
        - id: routes-client2-server
          uri: lb://eureka-client2
          predicates:
            - Path=/client/001/**

        - id: routes-order-server
          uri: lb://order-server
          predicates:
            - Path=/order/**
eureka:
  client:
    service-url: http://localhost:8761/eureka/
  instance:
    instance-id: gateway-server
    prefer-ip-address: true
